package ru.zoommax.portfolio.utils.position;

public enum SIDE {
    TOPofBOTTOM, BOTTOMofTOP, RIGHTofLEFT, LEFTofRIGHT,
    PARENTTOPLEFT, PARENTBOTTOMLEFT, PARENTTOPRIGHT, PARENTBOTTOMRIGHT,
    PARENTCENTER
}
